### ISSUE TITLE
Document services and functionality

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/wiki#13]
## Description
Add a description of the services and their planned functionality to the developer manuals in read the docs.
Should serve as base to communicate about services and functionality within the team and also with the customer.

## Acceptance Criteria
- [x] documentation is updated
- [x] Loic has been notified or did it himself

**Comment by myluki2000** [comment]
lgtm 👍

**Comment by bergdola** [comment]
@Keyshal-211 and me still have some open questions we would like to discuss: 

- Content service: in the description in the wiki, it is not clear, what happened to the tags? What should tags look like? The domain model states that Hints are content specific, which service handles the hints?

- Media service: what is the relation between hint and media pool (hint references media pool)? What is the exact idea of media pool (amount of media), when is this used?
