### ISSUE TITLE
Design: Path to course concept

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/wiki#34]
## Description
Work out a concept for work paths

**Comment by PaulBredl** [comment]
Decision -> Each chapter has multiple paths (called "Topic")-> each path is a linear, and contains of contents or group of contents ("TopicStage")
each chapter can define which paths need to be completed.



![Image](https://github.com/IT-REX-Platform/wiki/assets/34026908/fb5588bd-98ff-47d3-81d8-c09f0ee49cb4)

**Comment by PaulBredl** [comment]
![Image](https://github.com/IT-REX-Platform/wiki/assets/34026908/82b1e6d8-acf9-47f5-b2d8-14429f291f5a)
