### ISSUE TITLE
Create graphql schema for progress data

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/wiki#46]
## Parent

- [ ] #45 

## Description
Create the graphql schema for the user progress data.

## Acceptance Criteria
- [ ] Schema is documented

**Comment by PaulBredl** [comment]
The branches cannot be merged, as changes in the schema are not implemented yet in the services, so they would break. Instead, the adapted schemas are in their separate branches with draft pull requests that were reviewed.

**Comment by PaulBredl** [comment]
https://github.com/IT-REX-Platform/flashcard_service/pull/6
https://github.com/IT-REX-Platform/content_service/pull/20
https://github.com/IT-REX-Platform/media_service/pull/17
