### ISSUE TITLE
Setup Backend

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/wiki#8]
## Description
The backend team should set up a repository with the backend for the actual project

## Sub-issues / Children
https://github.com/IT-REX-Platform/wiki/issues/17
https://github.com/IT-REX-Platform/template-microservice/issues/1
https://github.com/IT-REX-Platform/wiki/issues/12
https://github.com/IT-REX-Platform/template-microservice/issues/3
https://github.com/IT-REX-Platform/template-microservice/issues/5
https://github.com/IT-REX-Platform/template-microservice/issues/7

**Comment by jessicaroth** [comment]
Template of Microservices will be established in the next sprint. The starting point was set today after the refinement of the project architecture. Will be tracked via smaller issues
